name: 'Languine'
description: 'Automate translations for your project'
author: 'Languine'

inputs:
  api-key:
    description: 'Languine API key'
    required: true
  project-id:
    description: 'Languine project ID'
    required: true
  cli-version:
    description: 'Version of Languine CLI to use'
    required: false
    default: 'latest'
  dev-mode:
    description: 'Enable development mode'
    required: false
    default: 'false'
  create-pull-request:
    description: 'Create a pull request instead of committing directly'
    required: false
    default: 'false'
  base-branch:
    description: 'Base branch to create pull request against or commit to'
    required: false
    default: 'main'
  commit-message:
    description: 'Custom commit message'
    required: false
    default: 'chore: update translations'
  pr-title:
    description: 'Title for the pull request'
    required: false
    default: 'chore: update translations'
  pr-body:
    description: 'Body content for the pull request'
    required: false
    default: 'This PR contains updated translations from Languine.'
  working-directory:
    description: 'Working directory relative to repository root'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LANGUINE_API_KEY: ${{ inputs.api-key }}
    LANGUINE_PROJECT_ID: ${{ inputs.project-id }}
    LANGUINE_CLI_VERSION: ${{ inputs.cli-version }}
    DEV_MODE: ${{ inputs.dev-mode }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
    INPUT_CREATE_PULL_REQUEST: ${{ inputs.create-pull-request }}
    INPUT_BASE_BRANCH: ${{ inputs.base-branch }}
    INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
    INPUT_PR_TITLE: ${{ inputs.pr-title }}
    INPUT_PR_BODY: ${{ inputs.pr-body }}

branding:
  icon: 'globe'
  color: 'blue'