name: 'Languine'
description: 'Automate translations for your project'
author: 'Languine'

inputs:
  api-key:
    description: 'Languine API key'
    required: true
  project-id:
    description: 'Languine project ID'
    required: true
  cli-version:
    description: 'Version of Languine CLI to use'
    required: false
    default: 'latest'
  dev-mode:
    description: 'Enable development mode'
    required: false
    default: 'false'
  create-pull-request:
    description: 'Create a pull request instead of committing directly'
    required: false
    default: 'false'
  commit-message:
    description: 'Custom commit message'
    required: false
  pr-title:
    description: 'Title for the pull request'
    required: false
  pr-body:
    description: 'Body content for the pull request'
    required: false
    default: 'This PR contains updated translations from Languine.'
  working-directory:
    description: 'Working directory relative to repository root'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LANGUINE_API_KEY: ${{ inputs.api-key }}
    LANGUINE_PROJECT_ID: ${{ inputs.project-id }}
    LANGUINE_CLI_VERSION: ${{ inputs.cli-version }}
    LANGUINE_WORKING_DIRECTORY: ${{ inputs.working-directory }}
    LANGUINE_CREATE_PULL_REQUEST: ${{ inputs.create-pull-request }}
    LANGUINE_COMMIT_MESSAGE: ${{ inputs.commit-message }}
    LANGUINE_PR_TITLE: ${{ inputs.pr-title }}
    LANGUINE_PR_BODY: ${{ inputs.pr-body }}
    DEV_MODE: ${{ inputs.dev-mode }}

branding:
  icon: 'globe'
  color: 'blue'