name: Deploy Web - Production
on:
  push:
    branches:
      - '**'
    paths:
      - apps/web/**
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🔄 Run Languine CLI
        uses: ./
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          api-key: ${{ secrets.LANGUINE_API_KEY }}
          project-id: ${{ secrets.LANGUINE_PROJECT_ID }}
          working-directory: apps/web
          cli-version: canary
          # create-pull-request: true
          dev-mode: true

