name: Deploy Web - Production
on:
  push:
    branches:
      - main
    paths:
      - apps/web/**
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🔄 Run Languine CLI
        uses: ./action
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          api-key: ${{ secrets.LANGUINE_API_KEY }}
          project-id: ${{ secrets.LANGUINE_PROJECT_ID }}
          dev-mode: ${{ env.ACT == 'true' }}
          working-directory: apps/web